name: Ray windows

on: workflow_dispatch

jobs:
  build-and-push-docker-image:
    permissions: write-all
    runs-on: ["self-hosted", "Windows", "noded"]
    steps:
    - name: Hello PWSH
      shell: pwsh
      run: |
        pwd
